set(HEADERS
SmoothCam/include/camera_states/thirdperson/dialogue/face_to_face.h
SmoothCam/include/camera_states/thirdperson/dialogue/oblivion.h
SmoothCam/include/camera_states/thirdperson/dialogue/skyrim.h
SmoothCam/include/camera_states/thirdperson/thirdperson.h
SmoothCam/include/camera_states/thirdperson/thirdperson_dialogue.h
SmoothCam/include/camera_states/thirdperson/thirdperson_vanity.h
SmoothCam/include/camera_states/base_first.h
SmoothCam/include/camera_states/base_third.h

SmoothCam/include/skyrimSE/AutoVanityState.h
SmoothCam/include/skyrimSE/HorseCameraState.h
SmoothCam/include/skyrimSE/PlayerCameraTransitionState.h
SmoothCam/include/skyrimSE/FreeCameraState.h
SmoothCam/include/skyrimSE/DragonCameraState.h
SmoothCam/include/skyrimSE/IMovementInterface.h

SmoothCam/include/crosshair/base.h
SmoothCam/include/crosshair/dot.h
SmoothCam/include/crosshair/skyrim.h

SmoothCam/include/debug/commands/dump_game_ini.h
SmoothCam/include/debug/commands/dump_game_perfs_ini.h
SmoothCam/include/debug/commands/get_setting.h
SmoothCam/include/debug/commands/help.h
SmoothCam/include/debug/commands/set_setting.h
SmoothCam/include/debug/console.h
SmoothCam/include/debug/eh.h
SmoothCam/include/debug/ICommand.h
SmoothCam/include/debug/registry.h

SmoothCam/include/render/models/dot.h
SmoothCam/include/render/models/skyrim_crosshair.h
SmoothCam/include/render/shaders/draw_fullscreen_texture.h
SmoothCam/include/render/shaders/shader_decl.h
SmoothCam/include/render/shaders/vertex_color_screen.h
SmoothCam/include/render/shaders/vertex_color_world.h

SmoothCam/include/render/cbuffer.h
SmoothCam/include/render/common.h
SmoothCam/include/render/d2d.h
SmoothCam/include/render/d3d_context.h
SmoothCam/include/render/dwrite.h
SmoothCam/include/render/gradbox.h
SmoothCam/include/render/line_drawer.h
SmoothCam/include/render/line_graph.h
SmoothCam/include/render/mesh_drawer.h
SmoothCam/include/render/model.h
SmoothCam/include/render/ninode_tree_display.h
SmoothCam/include/render/render_target.h
SmoothCam/include/render/shader_cache.h
SmoothCam/include/render/shader.h
SmoothCam/include/render/srv.h
SmoothCam/include/render/state_overlay.h
SmoothCam/include/render/texture2d.h
SmoothCam/include/render/vertex_buffer.h

SmoothCam/include/trackir/trackir.h

SmoothCam/include/arrow_fixes.h
SmoothCam/include/basicdetour.h
SmoothCam/include/camera.h
SmoothCam/include/code_analysis.h
SmoothCam/include/compat.h
SmoothCam/include/config.h
SmoothCam/include/crosshair.h
SmoothCam/include/hooks.h
SmoothCam/include/firstperson.h
SmoothCam/include/game_state.h
SmoothCam/include/main.h
SmoothCam/include/mmath.h
SmoothCam/include/modapi.h
SmoothCam/include/papyrus.h
SmoothCam/include/pch.h
SmoothCam/include/profile.h
SmoothCam/include/raycast.h
SmoothCam/include/resource.h
SmoothCam/include/SmoothCamAPI.h
SmoothCam/include/string_builder.h
SmoothCam/include/thirdperson.h
SmoothCam/include/timer.h
SmoothCam/include/util.h
SmoothCam/include/offset_ids.h
)