set(SOURCES
SmoothCam/source/camera_states/thirdperson/dialogue/face_to_face.cpp
SmoothCam/source/camera_states/thirdperson/dialogue/oblivion.cpp
SmoothCam/source/camera_states/thirdperson/dialogue/skyrim.cpp
SmoothCam/source/camera_states/thirdperson/thirdperson.cpp
SmoothCam/source/camera_states/thirdperson/thirdperson_dialogue.cpp
SmoothCam/source/camera_states/thirdperson/thirdperson_vanity.cpp
SmoothCam/source/camera_states/base_first.cpp
SmoothCam/source/camera_states/base_third.cpp

SmoothCam/source/crosshair/base.cpp
SmoothCam/source/crosshair/dot.cpp
SmoothCam/source/crosshair/skyrim.cpp

SmoothCam/source/debug/commands/dump_game_ini.cpp
SmoothCam/source/debug/commands/dump_game_perfs_ini.cpp
SmoothCam/source/debug/commands/get_setting.cpp
SmoothCam/source/debug/commands/help.cpp
SmoothCam/source/debug/commands/set_setting.cpp
SmoothCam/source/debug/console.cpp
SmoothCam/source/debug/eh.cpp
SmoothCam/source/debug/ICommand.cpp
SmoothCam/source/debug/registry.cpp

SmoothCam/source/render/cbuffer.cpp
SmoothCam/source/render/common.cpp
SmoothCam/source/render/d2d.cpp
SmoothCam/source/render/d3d_context.cpp
SmoothCam/source/render/dwrite.cpp
SmoothCam/source/render/gradbox.cpp
SmoothCam/source/render/line_drawer.cpp
SmoothCam/source/render/line_graph.cpp
SmoothCam/source/render/mesh_drawer.cpp
SmoothCam/source/render/model.cpp
SmoothCam/source/render/ninode_tree_display.cpp
SmoothCam/source/render/render_target.cpp
SmoothCam/source/render/shader_cache.cpp
SmoothCam/source/render/shader.cpp
SmoothCam/source/render/srv.cpp
SmoothCam/source/render/state_overlay.cpp
SmoothCam/source/render/texture2d.cpp
SmoothCam/source/render/vertex_buffer.cpp

SmoothCam/source/trackir/trackir.cpp

SmoothCam/source/arrow_fixes.cpp
SmoothCam/source/camera.cpp
SmoothCam/source/compat.cpp
SmoothCam/source/config.cpp
SmoothCam/source/crosshair.cpp
SmoothCam/source/detours.cpp
SmoothCam/source/firstperson.cpp
SmoothCam/source/game_state.cpp
SmoothCam/source/main.cpp
SmoothCam/source/mmath.cpp
SmoothCam/source/modapi.cpp
SmoothCam/source/papyrus.cpp
SmoothCam/source/pch.cpp
SmoothCam/source/raycast.cpp
SmoothCam/source/thirdperson.cpp
SmoothCam/source/timer.cpp
SmoothCam/source/offset_ids.cpp
SmoothCam/source/util.cpp
)